export const ACTIONS = {
    GET_POSTS: 'GET_POSTS',
    SET_POSTS: 'SET_POSTS',

    GET_COMMENTS: 'GET_COMMENTS',
    SET_COMMENTS: 'SET_COMMENTS',

    GET_USER_POSTS: 'GET_USER_POSTS',
    SET_USER_POSTS: 'SET_USER_POSTS',

    GET_COUNT_POSTS: 'GET_COUNT_POSTS',
    SET_COUNT_POSTS: 'SET_COUNT_POSTS',
}